=== Chabane/KramaFramework/target/classes/org/kramaframework/util/web-kramaframework_1_0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT krama-config    (js, css, views?, ajax-call?, js-dependencies?)>
		  <!--xmlns CDATA #FIXED "http:///kramaframework.org/Configuration"--> 

<!ELEMENT js EMPTY>
<!ATTLIST js 
	        location CDATA #REQUIRED>

<!ELEMENT css EMPTY>
<!ATTLIST css 
	        location CDATA #REQUIRED>

<!ELEMENT views (view*)>
<!ELEMENT view (#PCDATA) >
<!ATTLIST view  
		name NMTOKEN #REQUIRED
		class ID #REQUIRED>

<!ELEMENT ajax-call (class*)>
<!ELEMENT class (method+) >
<!ATTLIST class 
		name NMTOKEN #REQUIRED
		class ID #REQUIRED>
<!ELEMENT method (param*) >
<!ATTLIST method 
		name NMTOKEN #REQUIRED
		method NMTOKEN #REQUIRED>

<!ELEMENT param (#PCDATA) >
<!ATTLIST param 
		type (java.lang.Boolean|java.lang.Long|java.lang.String|java.lang.Float|java.lang.Double|java.lang.Integer|java.lang.Byte|java.lang.Character|java.lang.Short) #REQUIRED>

<!ELEMENT js-dependencies (js-dependency*)>
<!ELEMENT js-dependency (name, file, version?)>
<!ELEMENT name (#PCDATA) >
<!ELEMENT file (#PCDATA) >
<!ELEMENT version (#PCDATA) >

=== Chabane/KramaFramework/src/main/webapp/WEB-INF/krama-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE krama-config PUBLIC
    "-//Krama Framework//DTD Krama Framework Config 1.0//EN"
    "http://kramaframework.org/dtd/web-kramaframework_1_0.dtd">
    <!-- xmlns="http:///kramaframework.org/Configuration" --> 
<krama-config>
	<js location="js/" />
	<css location="css/" />
	
	<views>
		<view name="view" class="org.kramaframework.demo.View" />
		<view name="viewAjax" class="org.kramaframework.demo.ViewAjax" />
	</views> 

	<ajax-call>
		<class name="operation" class="org.kramaframework.demo.Operation">
			<method name="valeur" method="getValeur">
				<param type="java.lang.Integer" />
				<param type="java.lang.Integer" />
				<param type="java.lang.String" />
			</method>
		</class>
		<!-- http://localhost:8080/krama/result.aj?cName=operation&mName=valeur&nParam=3&param1=2&param2=3&param3=somme -->
	</ajax-call>

	<js-dependencies>
		<js-dependency>
			<name>jQuery</name>
			<file>jquery.js</file>
			<version>1.7.2</version>
		</js-dependency>
		<js-dependency>
			<name>Prototype</name>
			<file>prototype.js</file>
			<version>1.7</version>
		</js-dependency>
		<js-dependency>
			<name>Dojo</name>
			<file>dojo.js</file>
			<version>1.7.2</version>
		</js-dependency>
		<js-dependency>
			<name>Raphael</name>
			<file>raphael-min.js</file>
			<version>2.1.0</version>
		</js-dependency>
		<js-dependency>
			<name>Processing</name>
			<file>processing.js</file>
			<version>1.3.6</version>
		</js-dependency>
		<js-dependency>
			<name>jsPlumb</name>
			<file>jquery.jsPlumb.js</file>
			<version>1.3.8</version>
		</js-dependency>
		<js-dependency>
			<name>Dom-Drag</name>
			<file>dom-drag.js</file>
			<version>1.0</version>
		</js-dependency>
		<js-dependency>
			<name>Util</name>
			<file>util.js</file>
			<version>1.0</version>
		</js-dependency>
	</js-dependencies>
</krama-config>
